#pragma once

enum class StateMachine {
    STATE_REQUEST_ID,
    STATE_CONFIGURATION,
    STATE_MAIN,
    STATE_INTRO
};

enum class StateMainMenu {
    STATE_TEMP_HUMIDITY,
    STATE_VIBRATION,
    STATE_EXTREME_TEMP,
    STATE_ENVIRONMENT,
    STATE_SETTINGS,
    STATE_RESET
};